return dummy project path for anonymous files
Prevent errors thrown each time a character is
inserted into an anonymous file, causing latency
and errors in the sublime console:
  AttributeError: 'AnonymousFile' object has no attribute 'partition_folder'